## Understaing the CDAW API for WIND Spacecraft Plasma Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
from cdasws.cdasws import CdasWs
cdas = CdasWs()

In [3]:
dataset = 'WI_PM_3DP'

In [4]:
var_names = cdas.get_variable_names(dataset)
print('Variable names:', var_names)
print(type(var_names))

Variable names: ['P_DENS', 'P_VELS', 'P_TENS', 'P_TEMP', 'A_DENS', 'A_VELS', 'A_TENS', 'A_TEMP', 'E_RANGE', 'GAP', 'VALID', 'TIME']
<class 'list'>


In [5]:
# Define them as separate strings rather than a single list
start_time = '2012-11-03T00:00:00Z'
end_time = '2012-11-05T23:59:58Z'

print('Start time:', start_time)
print('End time:', end_time)

Start time: 2012-11-03T00:00:00Z
End time: 2012-11-05T23:59:58Z


In [6]:
# Pass them into get_data as two distinct arguments
status, data = cdas.get_data(dataset, var_names, start_time, end_time)

# print("HTTP Status:", status)
print(data)

/home/ayan-ubuntu/python/python3.8/Solar_Axis/lib/python3.8/site-packages/spacepy/time.py:2448: UserWarning: Leapseconds may be out of date. Use spacepy.toolbox.update(leapsecs=True)
  _read_leaps()


{'Epoch': VarCopy([datetime.datetime(2012, 11, 3, 0, 0, 1, 165000),
         datetime.datetime(2012, 11, 3, 0, 0, 4, 234000),
         datetime.datetime(2012, 11, 3, 0, 0, 7, 303000), ...,
         datetime.datetime(2012, 11, 5, 23, 59, 51, 680000),
         datetime.datetime(2012, 11, 5, 23, 59, 54, 748000),
         datetime.datetime(2012, 11, 5, 23, 59, 57, 817000)], dtype=object), 'P_DENS': VarCopy([5.309465 , 5.0910077, 5.066642 , ..., 5.874313 , 5.845499 ,
         5.9158316], dtype=float32), 'P_VELS': VarCopy([[-302.36624  ,   24.659592 ,    3.3974836],
         [-302.4495   ,   23.81431  ,    4.2468543],
         [-303.66257  ,   26.477705 ,    3.4139295],
         ...,
         [-300.4098   ,    0.8412013,   -6.7296104],
         [-301.8781   ,    0.8453128,   -7.6078153],
         [-300.4098   ,    0.8412013,   -7.5708117]], dtype=float32), 'P_TENS': VarCopy([[ 212.89227  ,  228.89256  ,  276.32288  , -103.30202  ,
            51.247597 ,  -42.859398 ],
         [ 214.19511  

In [7]:
print(type(data))

<class 'spacepy.pycdf.CDFCopy'>


In [8]:
if 'spacepy' in str(type(data)):
    #  see https://spacepy.github.io/datamodel.html
    print(var_names[0], '=', data[var_names[0]])
    print(data[var_names[0]].attrs)
else:
    #  see https://github.com/MAVENSDC/cdflib
    print(var_names[0], '=', data.data_vars[var_names[0]].values)
    print(data.data_vars[var_names[0]].attrs)


P_DENS = [5.309465  5.0910077 5.066642  ... 5.874313  5.845499  5.9158316]
{'FIELDNAM': 'Proton number density', 'CATDESC': 'Proton number density [values fill-noisy 5/19/2009-5/11/2010; 3/8-5/15/2012]', 'VAR_NOTES': 'Proton number density values are fill for time period 5/20/2009-5/11/2010; noisy 3/8/2012 04:37 to 5/15/2012 22:45]', 'DICT_KEY': 'density', 'VAR_TYPE': 'data', 'FORMAT': 'f7.2', 'UNITS': '#/cm3', 'SCALETYP': 'linear', 'FILLVAL': -1e+31, 'LABLAXIS': 'Dens_Protn_s/c', 'VALIDMIN': 0.0, 'VALIDMAX': 1000.0, 'DISPLAY_TYPE': 'time_series', 'DEPEND_0': 'Epoch', 'DIM_SIZES': 0}


In [9]:
print(var_names[1])
print(data[var_names[1]])
print(data[var_names[1]].attrs)

P_VELS
[[-302.36624     24.659592     3.3974836]
 [-302.4495      23.81431      4.2468543]
 [-303.66257     26.477705     3.4139295]
 ...
 [-300.4098       0.8412013   -6.7296104]
 [-301.8781       0.8453128   -7.6078153]
 [-300.4098       0.8412013   -7.5708117]]
{'FIELDNAM': 'Proton velocity vector', 'CATDESC': '---> Proton velocity vector (GSE)', 'VAR_NOTES': 'Proton velocity vector values are noisy for time period 5/15/2009-5/11/2010 and 3/8/2012 04:37 to 5/15/2012 22:45', 'DICT_KEY': 'velocity', 'VAR_TYPE': 'data', 'FORMAT': 'f8.2', 'UNITS': 'km/sec', 'SCALETYP': 'linear', 'FILLVAL': -1e+31, 'VALIDMIN': array([-4000., -4000., -4000.], dtype=float32), 'VALIDMAX': array([4000., 4000., 4000.], dtype=float32), 'DISPLAY_TYPE': 'time_series', 'DEPEND_0': 'Epoch', 'LABL_PTR_1': 'metavar0', 'DIM_SIZES': 3}


##  Making Data_frame

In [10]:
if 'spacepy' in str(type(data)):
    for var in var_names:
        print(var)

P_DENS
P_VELS
P_TENS
P_TEMP
A_DENS
A_VELS
A_TENS
A_TEMP
E_RANGE
GAP
VALID
TIME


In [11]:
data_dict = {}

if 'spacepy' in str(type(data)):
    for var in var_names:
        # 2. Assign the data values to the dictionary key
        data_dict[var] = data[var]
        
        # Optional: Print to confirm it worked
        print(f"Saved {var} - Data shape: {np.array(data[var]).shape}")



Saved P_DENS - Data shape: (114351,)
Saved P_VELS - Data shape: (114351, 3)
Saved P_TENS - Data shape: (114351, 6)
Saved P_TEMP - Data shape: (114351,)
Saved A_DENS - Data shape: (114351,)
Saved A_VELS - Data shape: (114351, 3)
Saved A_TENS - Data shape: (114351, 6)
Saved A_TEMP - Data shape: (114351,)
Saved E_RANGE - Data shape: (114351, 2)
Saved GAP - Data shape: (114351,)
Saved VALID - Data shape: (114351,)
Saved TIME - Data shape: (114351,)


In [12]:
data_dict

{'P_DENS': VarCopy([5.309465 , 5.0910077, 5.066642 , ..., 5.874313 , 5.845499 ,
          5.9158316], dtype=float32),
 'P_VELS': VarCopy([[-302.36624  ,   24.659592 ,    3.3974836],
          [-302.4495   ,   23.81431  ,    4.2468543],
          [-303.66257  ,   26.477705 ,    3.4139295],
          ...,
          [-300.4098   ,    0.8412013,   -6.7296104],
          [-301.8781   ,    0.8453128,   -7.6078153],
          [-300.4098   ,    0.8412013,   -7.5708117]], dtype=float32),
 'P_TENS': VarCopy([[ 212.89227  ,  228.89256  ,  276.32288  , -103.30202  ,
             51.247597 ,  -42.859398 ],
          [ 214.19511  ,  251.99446  ,  251.80237  ,  -95.35629  ,
             56.94169  ,  -42.859398 ],
          [ 202.66489  ,  258.99533  ,  262.44833  , -112.457954 ,
             68.33013  ,  -48.98217  ],
          ...,
          [ 148.01785  ,  232.3099   ,  187.73102  ,  -25.809847 ,
             11.388311 ,   -6.1227713],
          [ 133.96315  ,  241.81493  ,  198.31377  ,  -55.83806

In [13]:
import pandas as pd
import numpy as np

data_dict = {}

# ---------------------------------------------------------
# IF BLOCK: Handle SpacePy Data Model
# ---------------------------------------------------------
if 'spacepy' in str(type(data)):
    print("Detected SpacePy data. Processing...")
    for var in var_names:
        var_array = np.array(data[var])
        
        # Safely get attributes
        attrs = data[var].attrs if hasattr(data[var], 'attrs') else {}
        
        # Handle Fill Values
        if 'FILLVAL' in attrs:
            fill_val = attrs['FILLVAL']
            if var_array.dtype.kind in 'fc': 
                var_array = np.where(np.isclose(var_array, fill_val), np.nan, var_array)
            
        # --- 1D Arrays ---
        if len(var_array.shape) == 1:
            if 'Epoch' in data and len(var_array) == len(data['Epoch']):
                data_dict[var] = var_array
                
        # --- 2D Arrays (Vectors, Tensors) ---
        elif len(var_array.shape) == 2:
            num_components = var_array.shape[1]
            col_labels = []
            
            if 'LABL_PTR_1' in attrs:
                label_var_name = attrs['LABL_PTR_1']
                if label_var_name in data:
                    raw_labels = np.array(data[label_var_name])
                    for lbl in raw_labels:
                        clean_lbl = lbl.decode('utf-8') if isinstance(lbl, bytes) else str(lbl)
                        col_labels.append(clean_lbl.strip())
            
            for i in range(num_components):
                if len(col_labels) == num_components:
                    col_name = f"{var}_{col_labels[i]}"
                else:
                    col_name = f"{var}_{i}"
                    
                if 'Epoch' in data and len(var_array[:, i]) == len(data['Epoch']):
                    data_dict[col_name] = var_array[:, i]

# ---------------------------------------------------------
# ELSE BLOCK: Handle xarray Data Model (cdflib)
# ---------------------------------------------------------
else:
    print("Detected xarray data. Processing...")
    
    # In xarray, 'Epoch' is often a coordinate. Let's get its length safely.
    epoch_length = len(data['Epoch'].values) if 'Epoch' in data else 0
    
    for var in var_names:
        # Skip variables that might not be in data_vars (like coordinates)
        if var not in data.data_vars:
            continue
            
        # Extract the raw numpy array using .values
        var_array = data.data_vars[var].values
        
        # Safely get attributes
        attrs = data.data_vars[var].attrs
        
        # Handle Fill Values
        if 'FILLVAL' in attrs:
            fill_val = attrs['FILLVAL']
            if var_array.dtype.kind in 'fc': 
                var_array = np.where(np.isclose(var_array, fill_val), np.nan, var_array)
                
        # --- 1D Arrays ---
        if len(var_array.shape) == 1:
            if epoch_length > 0 and len(var_array) == epoch_length:
                data_dict[var] = var_array
                
        # --- 2D Arrays (Vectors, Tensors) ---
        elif len(var_array.shape) == 2:
            num_components = var_array.shape[1]
            col_labels = []
            
            if 'LABL_PTR_1' in attrs:
                label_var_name = attrs['LABL_PTR_1']
                
                # Fetch labels (can be in data_vars or coordinates in xarray)
                if label_var_name in data:
                    raw_labels = data[label_var_name].values
                    for lbl in raw_labels:
                        clean_lbl = lbl.decode('utf-8') if isinstance(lbl, bytes) else str(lbl)
                        col_labels.append(clean_lbl.strip())
            
            for i in range(num_components):
                if len(col_labels) == num_components:
                    col_name = f"{var}_{col_labels[i]}"
                else:
                    col_name = f"{var}_{i}"
                    
                if epoch_length > 0 and len(var_array[:, i]) == epoch_length:
                    data_dict[col_name] = var_array[:, i]

# ---------------------------------------------------------
# Create the DataFrame
# ---------------------------------------------------------
df = pd.DataFrame(data_dict)

if 'Epoch' in df.columns:
    df.set_index('Epoch', inplace=True)
elif 'Epoch' in data: # Fallback: explicitly add the Epoch from original data if missed
    if 'spacepy' in str(type(data)):
        df.index = np.array(data['Epoch'])
    else:
        df.index = data['Epoch'].values

print(f"\nDataFrame shape: {df.shape}")
print("Columns:", df.columns.tolist())

Detected SpacePy data. Processing...

DataFrame shape: (114351, 27)
Columns: ['P_DENS', 'P_VELS_VXGSE_Protn_s/c', 'P_VELS_VYGSE_Protn_s/c', 'P_VELS_VZGSE_Protn_s/c', 'P_TENS_ResVar_PrtnV_XX', 'P_TENS_ResVar_PrtnV_YY', 'P_TENS_ResVar_PrtnV_ZZ', 'P_TENS_ResVar_PrtnV_XY', 'P_TENS_ResVar_PrtnV_XZ', 'P_TENS_ResVar_PrtnV_YZ', 'P_TEMP', 'A_DENS', 'A_VELS_VXGSE_Alpha_s/c', 'A_VELS_VYGSE_Alpha_s/c', 'A_VELS_VZGSE_Alpha_s/c', 'A_TENS_ResVar_AlphaV_XX', 'A_TENS_ResVar_AlphaV_YY', 'A_TENS_ResVar_AlphaV_ZZ', 'A_TENS_ResVar_AlphaV_XY', 'A_TENS_ResVar_AlphaV_XZ', 'A_TENS_ResVar_AlphaV_YZ', 'A_TEMP', 'E_RANGE_Lower_E_Bound', 'E_RANGE_Upper_E_Bound', 'GAP', 'VALID', 'TIME']


In [14]:
df.head()

,P_DENS,P_VELS_VXGSE_Protn_s/c,P_VELS_VYGSE_Protn_s/c,P_VELS_VZGSE_Protn_s/c,P_TENS_ResVar_PrtnV_XX,P_TENS_ResVar_PrtnV_YY,P_TENS_ResVar_PrtnV_ZZ,P_TENS_ResVar_PrtnV_XY,P_TENS_ResVar_PrtnV_XZ,P_TENS_ResVar_PrtnV_YZ,...,A_TENS_ResVar_AlphaV_ZZ,A_TENS_ResVar_AlphaV_XY,A_TENS_ResVar_AlphaV_XZ,A_TENS_ResVar_AlphaV_YZ,A_TEMP,E_RANGE_Lower_E_Bound,E_RANGE_Upper_E_Bound,GAP,VALID,TIME
2012-11-03 00:00:01.165,5.309465,-302.366241,24.659592,3.397484,212.892273,228.892563,276.322876,-103.302017,51.247597,-42.859398,...,65.087265,-82.948151,11.388311,-12.245543,0.218754,256.028992,2036.844238,0,1,1.351901e+09
2012-11-03 00:00:04.234,5.091008,-302.449493,23.814310,4.246854,214.195114,251.994461,251.802368,-95.356293,56.941689,-42.859398,...,508.958771,-125.682037,-17.082533,0.000000,6.873053,256.028992,2036.844238,0,1,1.351901e+09
2012-11-03 00:00:07.303,5.066642,-303.662567,26.477705,3.413929,202.664886,258.995331,262.448334,-112.457954,68.330132,-48.982170,...,198.159241,-135.721451,37.012108,21.429699,5.432250,256.028992,2036.844238,0,1,1.351901e+09
2012-11-03 00:00:10.372,5.089029,-302.282990,25.504873,5.096225,200.198380,254.127151,270.188080,-105.346939,34.165066,-36.736629,...,153.855408,-91.500687,-96.800972,24.491085,4.729605,256.028992,2036.844238,0,1,1.351901e+09
2012-11-03 00:00:13.441,5.063373,-303.913544,23.929586,3.413929,228.363358,250.873428,256.281006,-104.252739,45.553375,-42.859398,...,244.035461,-36.115108,34.165066,-12.245543,4.894159,256.028992,2036.844238,0,1,1.351901e+09
